### ISSUE TITLE
Not found in Library Manager

### ISSUE THREAD

**Issue by bmcdonnell** [khoih-prog/FlashStorage_SAMD#1]
### Describe the bug

FlashStorage_SAMD library isn't listed in the Arduino IDE library manager.

### Steps to Reproduce

Per https://github.com/khoih-prog/FlashStorage_SAMD#use-arduino-library-manager,

> The best and easiest way is to use Arduino Library Manager. Search for FlashStorage_SAMD, then select / install the latest version.

### Expected behavior

Expected to find FlashStorage_SAMD library listed, probably adjacent to FlashStorage.

### Actual behavior

It's not anywhere in the list.

### Debug and AT-command log (if applicable)

N/A

### Screenshots

![image](https://user-images.githubusercontent.com/35789100/117554691-34bdd000-b027-11eb-86cf-fd4f0f80734b.png)

### Information

```
Arduino IDE version: 1.8.13
OS: Windows 10 version 1909 (OS Build 18363.1440)
Board: Adafruit Metro M4 AirLift
Board lib: Adafruit SAMD Boards library v1.6.7
```

> * `ESP8266`,`ESP32` or `STM32` Core Version (e.g. ESP8266 core v2.7.4, ESP32 v1.0.5 or STM32 v1.9.0)

I'm not sure if this applies. Where would I find it?

### Additional context

![image](https://user-images.githubusercontent.com/35789100/117554864-4358b700-b028-11eb-88c7-2a022c364c38.png)

**Comment by khoih-prog** [comment]
Hi @bmcdonnell 

Just post the request to include the library into Arduino IDE Library Manager. Check [**[Library Manager] Please add FlashStorage_SAMD library for SAMD21 and SAMD51** #11504](https://github.com/arduino/Arduino/issues/11504).

Hopefully it'll be included into **Library Manager** within 2 weeks. That's all I can do for now and the issue be closed.

Regards,

**Comment by khoih-prog** [comment]
Already listed in the Arduino IDE Library Manager.

![Selection_790](https://user-images.githubusercontent.com/57012152/117895255-fb39ce80-b28b-11eb-90ff-daf9bc92a7b2.png)
