### ISSUE TITLE
Updating values inside struct

### ISSUE THREAD

**Issue by zygisjas** [khoih-prog/FlashStorage_SAMD#2]
Not really an issue, nor request. I am just a bit confused how to use this example:

`FlashStorage_SAMD/examples/StoreNameAndSurname/StoreNameAndSurname.ino`

if I want to update the stored value later on?

**Comment by khoih-prog** [comment]
Try to use other examples to know what the functions and features you can use. Then apply to your case.

For example [**EEPROM_update** example](https://github.com/khoih-prog/FlashStorage_SAMD/blob/master/examples/EEPROM_update/EEPROM_update.ino)

**Comment by zygisjas** [comment]
> Try to use other examples to know what the functions and features you can use. Then apply to your case.
> 
> For example [**EEPROM_update** example](https://github.com/khoih-prog/FlashStorage_SAMD/blob/master/examples/EEPROM_update/EEPROM_update.ino)

Yes. I have looked at them but these examples don't really show how to do it. At the moment I ended up just updating the whole struct object. but this way does not seem to be efficient

**Comment by khoih-prog** [comment]
How about something similar to

```
typedef struct
{  
  char name[NAME_SIZE];  
  char surname[SURNAME_SIZE];
} Person;

EEPROM.put(storedAddress + sizeof(signature) + sizeof(owner.name), owner.surname);
// or
// EEPROM.put(storedAddress + sizeof(signature) + NAME_SIZE, owner.surname);

```

Examples are just basic examples, you have to study and find out a way to apply. Can not just expect everything must be shown in examples. If so, professional programmers are all jobless, just need **copier-pasters**.
