### ISSUE TITLE
Max EEPROM length SAMD51

### ISSUE THREAD

**Issue by TinManAkshay** [khoih-prog/FlashStorage_SAMD#4]
Hi, 

[Not an issue, just a discussion]

I am really pleased to say that these libraries are very well-structured. Although, I wanted to reach out to find out what's the maximum EEPROM length a SAMD51 MCU can have at a hardware level. I clearly see in one of you .h files, that you have defined 1024 as EEPROM length. Is it configurable or 1024 is the max value we can have?

Also, when I try to read EEPROM from the address "0", I got 0xFFFFFFFF on the serial monitor. Is that correct? 

Hope to hear from anybody soon.

Thanks,
Akshay

**Comment by khoih-prog** [comment]
Hi @TinManAkshay 

Thanks for using the library and your nice words.

For SAMD, thiis is actually emulated-EEPROM using a portion of Flash, not the real EEPROM.

The size if totally configurable by something similar to [**EEPROM_read.ino**#L32](https://github.com/khoih-prog/FlashStorage_SAMD/blob/master/examples/EEPROM_read/EEPROM_read.ino#L32) after uncommenting and changing according to your need (e.g. **4K**). **Default is 1K** if you don't specify in your code.

```
#define EEPROM_EMULATION_SIZE     (4 * 1024)
```

Remember this Flash is shared, so be careful don't use too much if not needed.

Run the examples to be familiar with the operation before writing your own code to avoid wasting time.

**Comment by TinManAkshay** [comment]
Hi @khoih-prog ,

Thank you for the response. I understood how it works now with the help of examples you provided. Also, I saw in your examples that you have been storing stuff at address 0. Can we have store stuff into multiple addresses(like 1, 2 , etc.) in an emulated EEPROM. Is that allowed to have multiple addresses such that I can store and retrieve different stuff from different addresses?

If Yes, what could be the max limit on having the Multiple addresses?

Thanks,
Akshay

**Comment by khoih-prog** [comment]
> Can we have store stuff into multiple addresses(like 1, 2 , etc.) in an emulated EEPROM. Is that allowed to have multiple addresses such that I can store and retrieve different stuff from different addresses?

It's emulated-EEPROM, so you can do **whatever** with it silimar to EEPROM, provided your code is programmed correctly. It's always better to write your code to try and verify.

It's also better to use complex struct and to write the whole struct, instead of writing every byte, one-by-one. Look at the examples.
