### ISSUE TITLE
Question: (Simulated) EEPROM looses its content on flashing new firmware

### ISSUE THREAD

**Issue by viktak** [khoih-prog/FlashStorage_SAMD#5]
First of all I wanted to say thanks for this library, and of course, hello! :)

Just wanted to confirm: as the title says, I assume this is normal, right?

I am new to the SAMD platform, but coming from an ESPxxxxx background (where there is an actual EEPROM for application data, which doesn't get deleted on every flash), and now I am trying to get my grips on a Wio Terminal.

The sample codes work nicely and I have learnt a lot from your code - thank you.

**Comment by khoih-prog** [comment]
Every time you upload a new sketch, the previous content of the FlashStorage, included **emulated-EEPROM** is erased.

Check [**The content of the FlashStorage is erased each time a new sketch is uploaded?**](https://github.com/khoih-prog/FlashStorage_SAMD#the-content-of-the-flashstorage-is-erased-each-time-a-new-sketch-is-uploaded)

**Comment by viktak** [comment]
Cool, thanks!
