### ISSUE TITLE
Not working example StoreNameAndSurname.ino with SAMD21 M0

### ISSUE THREAD

**Issue by proasnet** [khoih-prog/FlashStorage_SAMD#6]
### Describe the bug

Not save a data

### Steps to Reproduce

After entering data to serial monitor, write as saved. After plug power off and on again, open serial monitor, is needed enter names again. Not saved

### Expected behavior

After restart, names is readed from flash memory

### Information

Please ensure to specify the following:

* Arduino IDE version (e.g. 1.8.19) 
* `SAMD21 M0

**Comment by khoih-prog** [comment]
Hi @proasnet 

I don't know what you did wrong, but I'm still OK here with the same new board.

It's better to try with `Tools-> Adafruit SAMD -> Adafruit Feather M0 (SAMD21)`

### First Run

```
Start StoreNameAndSurname on SAMD_ZERO
FlashStorage_SAMD v1.3.2
EEPROM length: 1024
EEPROM is empty, writing WRITTEN_SIGNATURE and some example data:
Insert your name : Test_Name

Insert your surname : Test_Surname

<< Your name: Test_Name
. Your surname: Test_Surname
 >> have been saved. Thank you!
You can reset to check emulated-EEPROM data retention.
```

### After Reset or Power Off/On

```
Start StoreNameAndSurname on SAMD_ZERO
FlashStorage_SAMD v1.3.2
EEPROM length: 1024
Hi Test_Name
 Test_Surname
, nice to see you again :-)
Clearing WRITTEN_SIGNATURE for next try
Done clearing signature in emulated EEPROM. You can reset now
```
